#!/usr/bin/env python3
"""
Blood Pressure Classifier & Cardiovascular Metrics Tool
-------------------------------------------------------
This is a pure Python script demonstrating basic biomedical engineering metrics:
1. Systolic / Diastolic classification according to AHA (American Heart Association) guidelines.
2. Mean Arterial Pressure (MAP) estimation.
3. Pulse Pressure calculation.

Physiological Background:
- Systolic Pressure: Peak arterial pressure during cardiac contraction (systole).
- Diastolic Pressure: Minimum arterial pressure during cardiac relaxation (diastole).
- Pulse Pressure: Force generated by the heart each time it contracts (Systolic - Diastolic).
- Mean Arterial Pressure (MAP): The average pressure in an individual's arteries during a 
  single cardiac cycle. It is a critical perfusion indicator for organs.

No external dependencies are required. Run directly with:
    python blood_pressure_classifier.py
"""

def calculate_map(systolic: float, diastolic: float) -> float:
    """
    Calculates Mean Arterial Pressure (MAP).
    Formula: MAP = Diastolic + (1/3) * (Systolic - Diastolic)
    Since diastole lasts twice as long as systole at normal heart rates, 
    MAP is weighted more heavily toward diastolic pressure.
    """
    pulse_pressure = systolic - diastolic
    return diastolic + (pulse_pressure / 3.0)


def calculate_pulse_pressure(systolic: float, diastolic: float) -> float:
    """
    Calculates Pulse Pressure.
    Formula: PP = Systolic - Diastolic
    Elevated pulse pressure (usually > 60 mmHg) is a risk factor for cardiovascular disease,
    indicating arterial stiffness.
    """
    return systolic - diastolic


def classify_blood_pressure(systolic: float, diastolic: float) -> str:
    """
    Classifies blood pressure according to American Heart Association guidelines:
    - Normal: Systolic < 120 AND Diastolic < 80 mmHg
    - Elevated: Systolic 120-129 AND Diastolic < 80 mmHg
    - Hypertension Stage 1: Systolic 130-139 OR Diastolic 80-89 mmHg
    - Hypertension Stage 2: Systolic >= 140 OR Diastolic >= 90 mmHg
    - Hypertensive Crisis: Systolic > 180 and/or Diastolic > 120 mmHg (requires immediate attention)
    """
    if systolic > 180 or diastolic > 120:
        return "Hypertensive Crisis (Emergency)"
    elif systolic >= 140 or diastolic >= 90:
        return "Hypertension Stage 2"
    elif (130 <= systolic < 140) or (80 <= diastolic < 90):
        return "Hypertension Stage 1"
    elif (120 <= systolic < 130) and diastolic < 80:
        return "Elevated"
    elif systolic < 120 and diastolic < 80:
        return "Normal"
    else:
        # Fallback category for edge cases (e.g. Systolic < 120 and Diastolic 80-89 which is Stage 1)
        return "Stage 1 Hypertension (Borderline)"


def print_report(systolic: float, diastolic: float):
    """
    Prints a detailed diagnostic report.
    """
    classification = classify_blood_pressure(systolic, diastolic)
    map_val = calculate_map(systolic, diastolic)
    pulse_p = calculate_pulse_pressure(systolic, diastolic)
    
    print("-" * 50)
    print(f"BLOOD PRESSURE REPORT: {systolic:.0f}/{diastolic:.0f} mmHg")
    print("-" * 50)
    print(f"Classification:  {classification}")
    print(f"Pulse Pressure:  {pulse_p:.1f} mmHg (Normal range: 30 - 40 mmHg)")
    print(f"Mean Arterial:   {map_val:.1f} mmHg (Normal range: 70 - 100 mmHg)")
    
    # Clinical Interpretation
    if "Crisis" in classification:
        print("\n[WARNING] Critical reading. Seek medical attention immediately.")
    elif "Stage 2" in classification:
        print("\n[NOTE] Hypertension Stage 2 requires medical review and lifestyle/medication changes.")
    elif "Stage 1" in classification:
        print("\n[NOTE] Hypertension Stage 1 should be monitored and discussed with a physician.")
    elif "Elevated" in classification:
        print("\n[NOTE] Elevated blood pressure. Lifestyle modifications can help reduce it.")
    else:
        print("\n[INFO] Cardiovascular metrics are within normal ranges.")
    print("-" * 50)


def run_examples():
    """Runs a batch of clinical case studies."""
    print("Running BME Blood Pressure Example cases...")
    cases = [
        (115, 75),   # Normal
        (124, 78),   # Elevated
        (135, 82),   # Stage 1
        (145, 95),   # Stage 2
        (185, 125)   # Crisis
    ]
    for sys, dia in cases:
        print_report(sys, dia)
        print()


def interactive_mode():
    """Launches an interactive prompt."""
    print("\n--- Cardiovascular Metrics Calculator ---")
    while True:
        try:
            sys_input = input("\nEnter Systolic pressure (mmHg) [or 'q' to quit]: ").strip()
            if sys_input.lower() == 'q':
                break
            dia_input = input("Enter Diastolic pressure (mmHg): ").strip()
            
            sys = float(sys_input)
            dia = float(dia_input)
            
            if sys <= dia or sys <= 0 or dia <= 0:
                print("Error: Systolic must be greater than Diastolic, and both must be positive.")
                continue
                
            print_report(sys, dia)
        except ValueError:
            print("Error: Please enter valid numbers.")


if __name__ == "__main__":
    import sys
    # If arguments are passed, use them
    if len(sys.argv) == 3:
        try:
            sys_val = float(sys.argv[1])
            dia_val = float(sys.argv[2])
            print_report(sys_val, dia_val)
        except ValueError:
            print("Error: Please supply numeric values. Usage: python blood_pressure_classifier.py [systolic] [diastolic]")
    else:
        # Default behavior: run examples then prompt user
        run_examples()
        interactive_mode()
